- hosts: devserver
  vars:
    root_dir: /usr/share/nginx/html
    nginx_port: 8080
  tasks:
    - name: install nginx
      ansible.builtin.apt:
        name: nginx
        state: latest
      become: yes
    
    - name: update index page
      ansible.builtin.copy:
        src: ../files/nginx/index.html
        dest: "{{root_dir}}/index.html"
      notify:
        - restart nginx
      become: yes
    
    - name: update nginx config
      ansible.builtin.template:
        src: ../files/nginx/config.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - restart nginx
      become: yes
  
  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
      become: yes